services:
  - type: static
    name: bot-sports-empire-frontend
    env: static
    region: oregon
    plan: free
    publishDir: dist
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: "18.17.0"
